name: Build and Release
permissions:
    contents: write

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build
              run: |
                  npm install
                  npx @vscode/vsce package

            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.6
              with:
                  type: 'zip'
                  path: ./*.vsix
                  filename: 'release.zip'
                  recursive_exclusions: '*'

            - name: Upload Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: 'release.zip'
                  tag: ${{ steps.package-version.outputs.current-version}}
